import { expect } from 'chai';
import sinon, { SinonStub } from 'sinon';
import { PRCommentPoster, GitHubCommentAdapter, ConfirmAdapter } from './pr.comment.poster';
import {
  PRCommentPosterConfig,
  PRCommentPermissionError,
  PRCommentPostError,
  DEVMIND_COMMENT_MARKER,
  DEVMIND_FOOTER,
} from './pr.comment.types';
import { PRSummary } from '../pr-summary/pr.summary.types';

function makeSummary(overrides: Partial<PRSummary> = {}): PRSummary {
  return {
    id: 'pr-summary-owner-repo-42',
    owner: 'owner',
    repo: 'repo',
    prNumber: 42,
    prTitle: 'feat: add useQuery migration',
    prState: 'open',
    summary:
      '## Summary\nThis PR migrates useQuery.\n\n## Changes\n- Updated hooks\n\n## Impact\nLow risk.',
    chunkSummaries: [],
    wasChunked: false,
    foundryAgentId: 'agent-1',
    foundryThreadId: 'thread-1',
    templateVersion: '1.0.0',
    abVariant: null,
    status: 'complete',
    errorMessage: null,
    trigger: 'command',
    generatedAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 60000).toISOString(),
    prUpdatedAt: new Date().toISOString(),
    ...overrides,
  };
}

function makeGitHub(overrides: Partial<GitHubCommentAdapter> = {}): GitHubCommentAdapter {
  return {
    listPRComments: sinon.stub().resolves([]),
    createPRComment: sinon
      .stub()
      .resolves({ id: 101, url: 'https://github.com/owner/repo/pull/42#issuecomment-101' }),
    updatePRComment: sinon
      .stub()
      .resolves({ id: 101, url: 'https://github.com/owner/repo/pull/42#issuecomment-101' }),
    ...overrides,
  };
}

function makeConfirm(result = true): ConfirmAdapter {
  return { confirm: sinon.stub().resolves(result) };
}

function makePoster(
  config: PRCommentPosterConfig = {},
  github?: GitHubCommentAdapter,
  confirm?: ConfirmAdapter
): PRCommentPoster {
  return new PRCommentPoster(config, github ?? makeGitHub(), confirm ?? makeConfirm());
}

describe('PRCommentPoster', () => {
  afterEach(() => sinon.restore());

  describe('constructor', () => {
    it('creates an instance with default config', () => {
      expect(makePoster()).to.be.instanceOf(PRCommentPoster);
    });

    it('accepts custom footer', () => {
      expect(makePoster({ footer: 'Custom footer' })).to.be.instanceOf(PRCommentPoster);
    });

    it('accepts custom commentMarker', () => {
      expect(makePoster({ commentMarker: '<!-- custom -->' })).to.be.instanceOf(PRCommentPoster);
    });

    it('accepts enableLogging: false', () => {
      expect(makePoster({ enableLogging: false })).to.be.instanceOf(PRCommentPoster);
    });
  });

  describe('formatComment()', () => {
    it('returns a FormattedComment with body and charCount', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result).to.have.keys('body', 'charCount');
    });

    it('body contains the comment marker', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.body).to.include(DEVMIND_COMMENT_MARKER);
    });

    it('body contains a <details> block', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.body).to.include('<details>');
      expect(result.body).to.include('</details>');
    });

    it('body contains <summary> tag with PR number', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.body).to.include('<summary>');
      expect(result.body).to.include('#42');
    });

    it('body contains PR title', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.body).to.include('useQuery migration');
    });

    it('body contains the summary text', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.body).to.include('This PR migrates useQuery');
    });

    it('body contains the default footer', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.body).to.include('Generated by');
      expect(result.body).to.include('DevMind AI');
    });

    it('body uses custom footer when configured', () => {
      const result = makePoster({ footer: '\n\nCustom footer text' }).formatComment(makeSummary());
      expect(result.body).to.include('Custom footer text');
    });

    it('charCount equals body length', () => {
      const result = makePoster().formatComment(makeSummary());
      expect(result.charCount).to.equal(result.body.length);
    });

    it('shows complete badge for complete status', () => {
      const result = makePoster().formatComment(makeSummary({ status: 'complete' }));
      expect(result.body).to.include('✅');
    });

    it('shows partial badge for partial status', () => {
      const result = makePoster().formatComment(makeSummary({ status: 'partial' }));
      expect(result.body).to.include('⚠️');
    });

    it('shows failed badge for failed status', () => {
      const result = makePoster().formatComment(makeSummary({ status: 'failed' }));
      expect(result.body).to.include('❌');
    });

    it('includes chunk note for large PRs', () => {
      const summary = makeSummary({
        wasChunked: true,
        chunkSummaries: [
          { chunkIndex: 0, files: [], content: 'chunk 1', tokenCount: 100 },
          { chunkIndex: 1, files: [], content: 'chunk 2', tokenCount: 100 },
        ],
      });
      const result = makePoster().formatComment(summary);
      expect(result.body).to.include('Large PR');
      expect(result.body).to.include('2 chunks');
    });

    it('does not include chunk note for small PRs', () => {
      const result = makePoster().formatComment(makeSummary({ wasChunked: false }));
      expect(result.body).to.not.include('Large PR');
    });

    it('uses custom comment marker when configured', () => {
      const result = makePoster({ commentMarker: '<!-- custom-marker -->' }).formatComment(
        makeSummary()
      );
      expect(result.body).to.include('<!-- custom-marker -->');
    });

    it('escapes underscores in PR title', () => {
      const summary = makeSummary({ prTitle: 'feat: update_user_service' });
      const result = makePoster().formatComment(summary);
      expect(result.body).to.include('update\\_user\\_service');
    });
  });

  describe('findExistingComment()', () => {
    it('returns null when no comments exist', async () => {
      const github = makeGitHub({ listPRComments: sinon.stub().resolves([]) });
      const result = await makePoster({}, github).findExistingComment('owner', 'repo', 42);
      expect(result).to.be.null;
    });

    it('returns null when no DevMind comment found', async () => {
      const github = makeGitHub({
        listPRComments: sinon
          .stub()
          .resolves([
            { id: 1, body: 'Regular comment', author: 'user', url: 'https://github.com' },
          ]),
      });
      const result = await makePoster({}, github).findExistingComment('owner', 'repo', 42);
      expect(result).to.be.null;
    });

    it('returns comment ID when DevMind comment found', async () => {
      const github = makeGitHub({
        listPRComments: sinon.stub().resolves([
          {
            id: 99,
            body: `${DEVMIND_COMMENT_MARKER}\nOld summary`,
            author: 'devmind',
            url: 'https://github.com',
          },
        ]),
      });
      const result = await makePoster({}, github).findExistingComment('owner', 'repo', 42);
      expect(result).to.equal(99);
    });

    it('returns null when listPRComments throws', async () => {
      const github = makeGitHub({ listPRComments: sinon.stub().rejects(new Error('API error')) });
      const result = await makePoster({}, github).findExistingComment('owner', 'repo', 42);
      expect(result).to.be.null;
    });

    it('calls listPRComments with correct args', async () => {
      const github = makeGitHub();
      await makePoster({}, github).findExistingComment('owner', 'repo', 42);
      expect((github.listPRComments as SinonStub).calledWith('owner', 'repo', 42)).to.be.true;
    });

    it('uses custom marker when configured', async () => {
      const github = makeGitHub({
        listPRComments: sinon
          .stub()
          .resolves([{ id: 55, body: '<!-- custom -->\nOld summary', author: 'bot', url: '' }]),
      });
      const result = await makePoster(
        { commentMarker: '<!-- custom -->' },
        github
      ).findExistingComment('owner', 'repo', 42);
      expect(result).to.equal(55);
    });
  });

  describe('postSummary()', () => {
    it('returns null when user cancels', async () => {
      const result = await makePoster({}, undefined, makeConfirm(false)).postSummary(makeSummary());
      expect(result).to.be.null;
    });

    it('calls confirm with PR info', async () => {
      const confirm = makeConfirm(false);
      await makePoster({}, undefined, confirm).postSummary(makeSummary());
      expect((confirm.confirm as SinonStub).callCount).to.equal(1);
      const [msg] = (confirm.confirm as SinonStub).firstCall.args;
      expect(msg).to.include('owner/repo');
      expect(msg).to.include('#42');
    });

    it('creates new comment when no existing comment', async () => {
      const github = makeGitHub();
      await makePoster({}, github).postSummary(makeSummary());
      expect((github.createPRComment as SinonStub).callCount).to.equal(1);
      expect((github.updatePRComment as SinonStub).callCount).to.equal(0);
    });

    it('updates existing comment when one is found', async () => {
      const github = makeGitHub({
        listPRComments: sinon
          .stub()
          .resolves([{ id: 99, body: `${DEVMIND_COMMENT_MARKER}\nOld`, author: 'bot', url: '' }]),
      });
      await makePoster({}, github).postSummary(makeSummary());
      expect((github.updatePRComment as SinonStub).callCount).to.equal(1);
      expect((github.createPRComment as SinonStub).callCount).to.equal(0);
    });

    it('returns result with action: created for new comment', async () => {
      const result = await makePoster().postSummary(makeSummary());
      expect(result?.action).to.equal('created');
    });

    it('returns result with action: updated for existing comment', async () => {
      const github = makeGitHub({
        listPRComments: sinon
          .stub()
          .resolves([{ id: 99, body: `${DEVMIND_COMMENT_MARKER}\nOld`, author: 'bot', url: '' }]),
      });
      const result = await makePoster({}, github).postSummary(makeSummary());
      expect(result?.action).to.equal('updated');
    });

    it('returns result with commentId', async () => {
      const result = await makePoster().postSummary(makeSummary());
      expect(result?.commentId).to.equal(101);
    });

    it('returns result with commentUrl', async () => {
      const result = await makePoster().postSummary(makeSummary());
      expect(result?.commentUrl).to.include('github.com');
    });

    it('returns result with postedAt ISO string', async () => {
      const result = await makePoster().postSummary(makeSummary());
      expect(result?.postedAt).to.match(/^\d{4}-\d{2}-\d{2}T/);
    });

    it('passes formatted body to createPRComment', async () => {
      const github = makeGitHub();
      await makePoster({}, github).postSummary(makeSummary());
      const body = (github.createPRComment as SinonStub).firstCall.args[3];
      expect(body).to.include(DEVMIND_COMMENT_MARKER);
      expect(body).to.include('<details>');
    });

    it('passes formatted body to updatePRComment', async () => {
      const github = makeGitHub({
        listPRComments: sinon
          .stub()
          .resolves([{ id: 99, body: `${DEVMIND_COMMENT_MARKER}\nOld`, author: 'bot', url: '' }]),
      });
      await makePoster({}, github).postSummary(makeSummary());
      const body = (github.updatePRComment as SinonStub).firstCall.args[3];
      expect(body).to.include(DEVMIND_COMMENT_MARKER);
    });

    it('calls createPRComment with correct owner/repo/prNumber', async () => {
      const github = makeGitHub();
      await makePoster({}, github).postSummary(makeSummary());
      const [owner, repo, prNumber] = (github.createPRComment as SinonStub).firstCall.args;
      expect(owner).to.equal('owner');
      expect(repo).to.equal('repo');
      expect(prNumber).to.equal(42);
    });

    it('calls updatePRComment with existing comment ID', async () => {
      const github = makeGitHub({
        listPRComments: sinon
          .stub()
          .resolves([{ id: 77, body: `${DEVMIND_COMMENT_MARKER}`, author: 'bot', url: '' }]),
      });
      await makePoster({}, github).postSummary(makeSummary());
      const [, , commentId] = (github.updatePRComment as SinonStub).firstCall.args;
      expect(commentId).to.equal(77);
    });

    it('throws PRCommentPermissionError on 403', async () => {
      const err = Object.assign(new Error('Forbidden'), { status: 403 });
      const github = makeGitHub({ createPRComment: sinon.stub().rejects(err) });
      let threw = false;
      try {
        await makePoster({}, github).postSummary(makeSummary());
      } catch (e: any) {
        threw = true;
        expect(e.name).to.equal('PRCommentPermissionError');
      }
      expect(threw).to.be.true;
    });

    it('throws PRCommentPermissionError on 401', async () => {
      const err = Object.assign(new Error('Unauthorized'), { status: 401 });
      const github = makeGitHub({ createPRComment: sinon.stub().rejects(err) });
      let threw = false;
      try {
        await makePoster({}, github).postSummary(makeSummary());
      } catch (e: any) {
        threw = true;
        expect(e.name).to.equal('PRCommentPermissionError');
      }
      expect(threw).to.be.true;
    });

    it('throws PRCommentPostError on generic error', async () => {
      const github = makeGitHub({
        createPRComment: sinon.stub().rejects(new Error('Network error')),
      });
      let threw = false;
      try {
        await makePoster({}, github).postSummary(makeSummary());
      } catch (e: any) {
        threw = true;
        expect(e.name).to.equal('PRCommentPostError');
      }
      expect(threw).to.be.true;
    });

    it('PRCommentPermissionError message includes owner/repo/prNumber', async () => {
      const err = Object.assign(new Error('Forbidden'), { status: 403 });
      const github = makeGitHub({ createPRComment: sinon.stub().rejects(err) });
      try {
        await makePoster({}, github).postSummary(makeSummary());
      } catch (e: any) {
        expect(e.message).to.include('owner/repo');
        expect(e.message).to.include('#42');
      }
    });
  });

  describe('isPermissionError()', () => {
    it('returns true for status 403', () => {
      expect(makePoster().isPermissionError({ status: 403 })).to.be.true;
    });

    it('returns true for status 401', () => {
      expect(makePoster().isPermissionError({ status: 401 })).to.be.true;
    });

    it('returns true for "forbidden" in message', () => {
      expect(makePoster().isPermissionError({ message: 'Forbidden: token expired' })).to.be.true;
    });

    it('returns true for "not authorized" in message', () => {
      expect(makePoster().isPermissionError({ message: 'User is not authorized' })).to.be.true;
    });

    it('returns true for "resource not accessible" in message', () => {
      expect(makePoster().isPermissionError({ message: 'Resource not accessible by integration' }))
        .to.be.true;
    });

    it('returns false for status 404', () => {
      expect(makePoster().isPermissionError({ status: 404 })).to.be.false;
    });

    it('returns false for status 500', () => {
      expect(makePoster().isPermissionError({ status: 500 })).to.be.false;
    });

    it('returns false for null', () => {
      expect(makePoster().isPermissionError(null)).to.be.false;
    });

    it('returns false for plain string error', () => {
      expect(makePoster().isPermissionError('some error')).to.be.false;
    });

    it('returns false for network error message', () => {
      expect(makePoster().isPermissionError({ message: 'Network timeout' })).to.be.false;
    });
  });

  describe('getCommentPreview()', () => {
    it('returns a string', () => {
      expect(makePoster().getCommentPreview(makeSummary())).to.be.a('string');
    });

    it('returns at most 503 chars (500 + ellipsis)', () => {
      const longSummary = makeSummary({ summary: 'x'.repeat(2000) });
      const preview = makePoster().getCommentPreview(longSummary);
      expect(preview.length).to.be.at.most(504);
    });

    it('returns full content for short summaries', () => {
      const preview = makePoster().getCommentPreview(makeSummary());
      expect(preview).to.not.include('…');
    });

    it('appends ellipsis for long summaries', () => {
      const longSummary = makeSummary({ summary: 'x'.repeat(2000) });
      const preview = makePoster().getCommentPreview(longSummary);
      expect(preview).to.include('…');
    });

    it('includes comment marker in preview', () => {
      const preview = makePoster().getCommentPreview(makeSummary());
      expect(preview).to.include(DEVMIND_COMMENT_MARKER);
    });
  });

  describe('buildCommentMarker()', () => {
    it('returns default marker', () => {
      expect(makePoster().buildCommentMarker()).to.equal(DEVMIND_COMMENT_MARKER);
    });

    it('returns custom marker when configured', () => {
      expect(makePoster({ commentMarker: '<!-- custom -->' }).buildCommentMarker()).to.equal(
        '<!-- custom -->'
      );
    });
  });

  describe('DEVMIND_COMMENT_MARKER', () => {
    it('is an HTML comment', () => {
      expect(DEVMIND_COMMENT_MARKER.startsWith('<!--')).to.be.true;
      expect(DEVMIND_COMMENT_MARKER).to.include('-->');
    });

    it('includes devmind identifier', () => {
      expect(DEVMIND_COMMENT_MARKER.toLowerCase()).to.include('devmind');
    });
  });

  describe('DEVMIND_FOOTER', () => {
    it('includes DevMind AI', () => {
      expect(DEVMIND_FOOTER).to.include('DevMind AI');
    });

    it('includes DevMind', () => {
      expect(DEVMIND_FOOTER).to.include('DevMind');
    });

    it('starts with newlines for spacing', () => {
      expect(DEVMIND_FOOTER).to.include('\n');
    });
  });

  describe('PRCommentPermissionError', () => {
    it('has correct name', () => {
      const e = new PRCommentPermissionError('owner', 'repo', 42);
      expect(e.name).to.equal('PRCommentPermissionError');
    });

    it('includes owner, repo, prNumber in message', () => {
      const e = new PRCommentPermissionError('owner', 'repo', 42);
      expect(e.message).to.include('owner/repo');
      expect(e.message).to.include('#42');
    });

    it('exposes owner, repo, prNumber properties', () => {
      const e = new PRCommentPermissionError('owner', 'repo', 42);
      expect(e.owner).to.equal('owner');
      expect(e.repo).to.equal('repo');
      expect(e.prNumber).to.equal(42);
    });
  });

  describe('PRCommentPostError', () => {
    it('has correct name', () => {
      const e = new PRCommentPostError(42, 'timeout');
      expect(e.name).to.equal('PRCommentPostError');
    });

    it('includes prNumber in message', () => {
      const e = new PRCommentPostError(42, 'timeout');
      expect(e.message).to.include('#42');
    });

    it('includes cause in message', () => {
      const e = new PRCommentPostError(42, 'Network timeout');
      expect(e.message).to.include('Network timeout');
    });
  });
});
