import { PRSummary } from '../pr-summary/pr.summary.types';

export interface PRCommentPosterConfig {
  footer?: string;
  commentMarker?: string;
  enableLogging?: boolean;
}

export type PostAction = 'created' | 'updated';

export interface PostCommentResult {
  commentId: number;
  action: PostAction;
  commentUrl: string;
  postedAt: string;
}

export interface FormattedComment {
  body: string;
  charCount: number;
}

export class PRCommentPermissionError extends Error {
  constructor(
    public readonly owner: string,
    public readonly repo: string,
    public readonly prNumber: number
  ) {
    super(
      `Permission denied: cannot post comments on ${owner}/${repo} PR #${prNumber}. ` +
        `Ensure your GitHub token has write access to issues/pull requests.`
    );
    this.name = 'PRCommentPermissionError';
  }
}

export class PRCommentPostError extends Error {
  constructor(
    public readonly prNumber: number,
    cause: string
  ) {
    super(`Failed to post comment on PR #${prNumber}: ${cause}`);
    this.name = 'PRCommentPostError';
  }
}

export const DEVMIND_FOOTER = '\n\n---\n*Generated by DevMind AI · v1*';

export const DEVMIND_COMMENT_MARKER = '<!-- devmind-pr-summary -->';
